#### 2주차 보충학습_ 기술 통계 분석과 그래프

In [ ]:
# 데이터 출처: https://archive.ics.uci.edu/dataset/186/wine+quality
# %pip install ucimlrepo

# 데이터 불러오기
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
wine_quality = fetch_ucirepo(id=186) 
  
# data (as pandas dataframes) 
X = wine_quality.data.features 
y = wine_quality.data.targets 
  
# metadata 
print(wine_quality.metadata) 
  
# variable information 
print(wine_quality.variables)

{'uci_id': 186, 'name': 'Wine Quality', 'repository_url': 'https://archive.ics.uci.edu/dataset/186/wine+quality', 'data_url': 'https://archive.ics.uci.edu/static/public/186/data.csv', 'abstract': 'Two datasets are included, related to red and white vinho verde wine samples, from the north of Portugal. The goal is to model wine quality based on physicochemical tests (see [Cortez et al., 2009], http://www3.dsi.uminho.pt/pcortez/wine/).', 'area': 'Business', 'tasks': ['Classification', 'Regression'], 'characteristics': ['Multivariate'], 'num_instances': 4898, 'num_features': 11, 'feature_types': ['Real'], 'demographics': [], 'target_col': ['quality'], 'index_col': None, 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 2009, 'last_updated': 'Wed Nov 15 2023', 'dataset_doi': '10.24432/C56S3T', 'creators': ['Paulo Cortez', 'A. Cerdeira', 'F. Almeida', 'T. Matos', 'J. Reis'], 'intro_paper': {'ID': 252, 'type': 'NATIVE', 'title': 'Modeling wine preferences by data mining from physicochemical properties', 'authors': 'P. Cortez, A. Cerdeira, Fernando Almeida, Telmo Matos, J. Reis', 'venue': 'Decision Support Systems', 'year': 2009, 'journal': None, 'DOI': None, 'URL': 'https://www.semanticscholar.org/paper/Modeling-wine-preferences-by-data-mining-from-Cortez-Cerdeira/bf15a0ccc14ac1deb5cea570c870389c16be019c', 'sha': None, 'corpus': None, 'arxiv': None, 'mag': None, 'acl': None, 'pmid': None, 'pmcid': None}, 'additional_info': {'summary': 'The two datasets are related to red and white variants of the Portuguese "Vinho Verde" wine. For more details, consult: http://www.vinhoverde.pt/en/ or the reference [Cortez et al., 2009].  Due to privacy and logistic issues, only physicochemical (inputs) and sensory (the output) variables are available (e.g. there is no data about grape types, wine brand, wine selling price, etc.).\n\nThese datasets can be viewed as classification or regression tasks.  The classes are ordered and not balanced (e.g. there are many more normal wines than excellent or poor ones). Outlier detection algorithms could be used to detect the few excellent or poor wines. Also, we are not sure if all input variables are relevant. So it could be interesting to test feature selection methods.\n', 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': 'For more information, read [Cortez et al., 2009].\r\nInput variables (based on physicochemical tests):\r\n   1 - fixed acidity\r\n   2 - volatile acidity\r\n   3 - citric acid\r\n   4 - residual sugar\r\n   5 - chlorides\r\n   6 - free sulfur dioxide\r\n   7 - total sulfur dioxide\r\n   8 - density\r\n   9 - pH\r\n   10 - sulphates\r\n   11 - alcohol\r\nOutput variable (based on sensory data): \r\n   12 - quality (score between 0 and 10)', 'citation': None}}
                    name     role         type demographic  \
0          fixed_acidity  Feature   Continuous        None
1       volatile_acidity  Feature   Continuous        None
2            citric_acid  Feature   Continuous        None
3         residual_sugar  Feature   Continuous        None
4              chlorides  Feature   Continuous        None
5    free_sulfur_dioxide  Feature   Continuous        None
6   total_sulfur_dioxide  Feature   Continuous        None
7                density  Feature   Continuous        None
8                     pH  Feature   Continuous        None
9              sulphates  Feature   Continuous        None
10               alcohol  Feature   Continuous        None
11               quality   Target      Integer        None
12                 color    Other  Categorical        None

               description units missing_values
0                      NaN  None             no
1                      NaN  None             no
2                      NaN  None             no
3                      NaN  None             no
4                      NaN  None             no
5                      NaN  None             no
6                      NaN  None             no
7                      NaN  None             no
8                      NaN  None             no
9                      NaN  None             no
10                     NaN  None             no
11  score between 0 and 10  None             no
12            red or white  None             no

In [ ]:
# 라이브러리 불러오기

Collecting statsmodels
  Downloading statsmodels-0.15.0.tar.gz (15.7 MB)
     ---------------------------------------- 0.0/15.7 MB ? eta -:--:--
     ----------------------- ---------------- 9.4/15.7 MB 53.3 MB/s eta 0:00:01
     ---------------------------------------- 15.7/15.7 MB 49.4 MB/s  0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'
Note: you may need to restart the kernel to use updated packages.

  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      + meson setup C:\Users\jihun\AppData\Local\Temp\pip-install-_4bbwlwz\statsmodels_cd2ff88a7166462c9a6a6b8c344677a2 C:\Users\jihun\AppData\Local\Temp\pip-install-_4bbwlwz\statsmodels_cd2ff88a7166462c9a6a6b8c344677a2\.mesonpy-5vc8gnll -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --vsenv --native-file=C:\Users\jihun\AppData\Local\Temp\pip-install-_4bbwlwz\statsmodels_cd2ff88a7166462c9a6a6b8c344677a2\.mesonpy-5vc8gnll\meson-python-native-file.ini
      The Meson build system
      Version: 1.12.1
      Source dir: C:\Users\jihun\AppData\Local\Temp\pip-install-_4bbwlwz\statsmodels_cd2ff88a7166462c9a6a6b8c344677a2
      Build dir: C:\Users\jihun\AppData\Local\Temp\pip-install-_4bbwlwz\statsmodels_cd2ff88a7166462c9a6a6b8c344677a2\.mesonpy-5vc8gnll
      Build type: native build

      ..\meson.build:1:0: ERROR: Could not find C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe

      A full log can be found at C:\Users\jihun\AppData\Local\Temp\pip-install-_4bbwlwz\statsmodels_cd2ff88a7166462c9a6a6b8c344677a2\.mesonpy-5vc8gnll\meson-logs\meson-log.txt
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> statsmodels

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

In [ ]:
df = wine_quality.data.original

print(df.shape)
print(df.info())
print(df.describe())
print()

df.head()

(6497, 13)
<class 'pandas.DataFrame'>
RangeIndex: 6497 entries, 0 to 6496
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed_acidity         6497 non-null   float64
 1   volatile_acidity      6497 non-null   float64
 2   citric_acid           6497 non-null   float64
 3   residual_sugar        6497 non-null   float64
 4   chlorides             6497 non-null   float64
 5   free_sulfur_dioxide   6497 non-null   float64
 6   total_sulfur_dioxide  6497 non-null   float64
 7   density               6497 non-null   float64
 8   pH                    6497 non-null   float64
 9   sulphates             6497 non-null   float64
 10  alcohol               6497 non-null   float64
 11  quality               6497 non-null   int64
 12  color                 6497 non-null   str
dtypes: float64(11), int64(1), str(1)
memory usage: 688.6 KB
None
       fixed_acidity  volatile_acidity  citric_acid  residual_sugar  \
count    6497.000000       6497.000000  6497.000000     6497.000000
mean        7.215307          0.339666     0.318633        5.443235
std         1.296434          0.164636     0.145318        4.757804
min         3.800000          0.080000     0.000000        0.600000
25%         6.400000          0.230000     0.250000        1.800000
50%         7.000000          0.290000     0.310000        3.000000
75%         7.700000          0.400000     0.390000        8.100000
max        15.900000          1.580000     1.660000       65.800000

         chlorides  free_sulfur_dioxide  total_sulfur_dioxide      density  \
count  6497.000000          6497.000000           6497.000000  6497.000000
mean      0.056034            30.525319            115.744574     0.994697
std       0.035034            17.749400             56.521855     0.002999
min       0.009000             1.000000              6.000000     0.987110
25%       0.038000            17.000000             77.000000     0.992340
50%       0.047000            29.000000            118.000000     0.994890
75%       0.065000            41.000000            156.000000     0.996990
max       0.611000           289.000000            440.000000     1.038980

                pH    sulphates      alcohol      quality
count  6497.000000  6497.000000  6497.000000  6497.000000
mean      3.218501     0.531268    10.491801     5.818378
std       0.160787     0.148806     1.192712     0.873255
min       2.720000     0.220000     8.000000     3.000000
25%       3.110000     0.430000     9.500000     5.000000
50%       3.210000     0.510000    10.300000     6.000000
75%       3.320000     0.600000    11.300000     6.000000
max       4.010000     2.000000    14.900000     9.000000

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,color
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,red
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red

In [7]:
print(df["color"].unique())

<ArrowStringArray>
['red', 'white']
Length: 2, dtype: str

In [8]:
red_df = df[df["color"] == "red"].drop(columns="color").copy()
white_df = df[df["color"] == "white"].drop(columns="color").copy()

red_df.insert(0, "type", "red")
white_df.insert(0, "type", "white")

print(red_df.head())
print(white_df.head())

  type  fixed_acidity  volatile_acidity  citric_acid  residual_sugar  \
0  red            7.4              0.70         0.00             1.9
1  red            7.8              0.88         0.00             2.6
2  red            7.8              0.76         0.04             2.3
3  red           11.2              0.28         0.56             1.9
4  red            7.4              0.70         0.00             1.9

   chlorides  free_sulfur_dioxide  total_sulfur_dioxide  density    pH  \
0      0.076                 11.0                  34.0   0.9978  3.51
1      0.098                 25.0                  67.0   0.9968  3.20
2      0.092                 15.0                  54.0   0.9970  3.26
3      0.075                 17.0                  60.0   0.9980  3.16
4      0.076                 11.0                  34.0   0.9978  3.51

   sulphates  alcohol  quality
0       0.56      9.4        5
1       0.68      9.8        5
2       0.65      9.8        5
3       0.58      9.8        6
4       0.56      9.4        5
       type  fixed_acidity  volatile_acidity  citric_acid  residual_sugar  \
1599  white            7.0              0.27         0.36            20.7
1600  white            6.3              0.30         0.34             1.6
1601  white            8.1              0.28         0.40             6.9
1602  white            7.2              0.23         0.32             8.5
1603  white            7.2              0.23         0.32             8.5

      chlorides  free_sulfur_dioxide  total_sulfur_dioxide  density    pH  \
1599      0.045                 45.0                 170.0   1.0010  3.00
1600      0.049                 14.0                 132.0   0.9940  3.30
1601      0.050                 30.0                  97.0   0.9951  3.26
1602      0.058                 47.0                 186.0   0.9956  3.19
1603      0.058                 47.0                 186.0   0.9956  3.19

      sulphates  alcohol  quality
1599       0.45      8.8        6
1600       0.49      9.5        6
1601       0.44     10.1        6
1602       0.40      9.9        6
1603       0.40      9.9        6

In [9]:
print(red_df.shape)
print(white_df.shape)

(1599, 13)
(4898, 13)

In [20]:
import pandas as pd
wine = pd.concat([red_df, white_df])
wine.shape

(6497, 13)

In [ ]:
import os

os.makedirs("./wine_regression", exist_ok=True)
wine.to_csv("./wine_regression/wine.csv", index=False)

In [13]:
print(wine.info())

<class 'pandas.DataFrame'>
RangeIndex: 6497 entries, 0 to 6496
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   type                  6497 non-null   str
 1   fixed_acidity         6497 non-null   float64
 2   volatile_acidity      6497 non-null   float64
 3   citric_acid           6497 non-null   float64
 4   residual_sugar        6497 non-null   float64
 5   chlorides             6497 non-null   float64
 6   free_sulfur_dioxide   6497 non-null   float64
 7   total_sulfur_dioxide  6497 non-null   float64
 8   density               6497 non-null   float64
 9   pH                    6497 non-null   float64
 10  sulphates             6497 non-null   float64
 11  alcohol               6497 non-null   float64
 12  quality               6497 non-null   int64
dtypes: float64(11), int64(1), str(1)
memory usage: 689.4 KB
None

In [14]:
display(wine.describe())

print(sorted(wine.quality.unique().tolist()))

display(wine.quality.value_counts())

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
count,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000
mean,7.215307,0.339666,0.318633,5.443235,0.056034,30.525319,115.744574,0.994697,3.218501,0.531268,10.491801,5.818378
std,1.296434,0.164636,0.145318,4.757804,0.035034,17.749400,56.521855,0.002999,0.160787,0.148806,1.192712,0.873255
min,3.800000,0.080000,0.000000,0.600000,0.009000,1.000000,6.000000,0.987110,2.720000,0.220000,8.000000,3.000000
25%,6.400000,0.230000,0.250000,1.800000,0.038000,17.000000,77.000000,0.992340,3.110000,0.430000,9.500000,5.000000
50%,7.000000,0.290000,0.310000,3.000000,0.047000,29.000000,118.000000,0.994890,3.210000,0.510000,10.300000,6.000000
75%,7.700000,0.400000,0.390000,8.100000,0.065000,41.000000,156.000000,0.996990,3.320000,0.600000,11.300000,6.000000
max,15.900000,1.580000,1.660000,65.800000,0.611000,289.000000,440.000000,1.038980,4.010000,2.000000,14.900000,9.000000

[3, 4, 5, 6, 7, 8, 9]

quality
6    2836
5    2138
7    1079
4     216
8     193
3      30
9       5
Name: count, dtype: int64

In [16]:
display(wine.groupby('type')['quality'].describe())

print(wine.groupby('type')['quality'].mean())
print(wine.groupby('type')['quality'].std())
print(wine.groupby('type')['quality'].agg(['mean', 'std']))

        count      mean       std  min  25%  50%  75%  max
type
red    1599.0  5.636023  0.807569  3.0  5.0  6.0  6.0  8.0
white  4898.0  5.877909  0.885639  3.0  5.0  6.0  6.0  9.0

type
red      5.636023
white    5.877909
Name: quality, dtype: float64
type
red      0.807569
white    0.885639
Name: quality, dtype: float64
           mean       std
type
red    5.636023  0.807569
white  5.877909  0.885639

In [ ]:
from scipy import stats
from statsmodels.formula.api import ols,glm

ModuleNotFoundError: No module named 'statsmodels'